### ISSUE TITLE
Capacitor 5 Support

### ISSUE THREAD

**Issue by iAmServer** [hypertrack/sdk-ionic-capacitor#11]
This plugin does not work with capacitor 5, please look into this as soon as possible

**Comment by pavel-kuznetsov-hypertrack** [comment]
Now we [support Capacitor 6](https://github.com/hypertrack/quickstart-ionic-capacitor/blob/280f7b85199426c1827f5a7bbc8b0b01f2e0dcd3/package.json#L24), I assume this issue is resolved. If you have any issues, please post the full error message.
